### ISSUE TITLE
A Compare-Aggregate Model with Dynamic-Clip Attention for Answer Selection

### ISSUE THREAD

**Issue by dyuyang** [NTMC-Community/MatchZoo-py#104]
- [ ] I checked to make sure that this is not a duplicate issue
- [ ] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/NTMC-Community/awaresome-neural-models-for-semantic-match))

### Additional Information
Other things you want the developers to know.

**Comment by Chriskuei** [comment]
#107
