### ISSUE TITLE
Inefficient DataLoader

### ISSUE THREAD

**Issue by matthew-z** [NTMC-Community/MatchZoo-py#109]
- [x] I checked to make sure that this is not a duplicate issue
- [x] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/NTMC-Community/awaresome-neural-models-for-semantic-match))

### Is your feature request related to a problem? Please describe.
They way that dataloader reads elements from dataset and datapack is very inefficient in pytorch Matchzoo. The dataloader retrieves each element from the datapack separately,  and group them into a batch. 

However, the `__getitem__ `of datapack is quite expensive. To return a batch of 1000 elements, the `__getitem__ `method of datapack will be called 1000 times (the argument is an index at each time), and it usually takes 5-10 seconds to produce a single batch (when the batch size = 1000). 

In contrast, in the TF version of Matchzoo, the `__getitem__` method of datapack will be called with a list of indices together, so each batch will only call it once. As a result, the DataGenerator is much more efficient than the DataLoader.

### Describe the solution you'd like
Avoid using the auto-batching provided by DataLoader. Instead, the dataset should pass batches to Dataloader: https://pytorch.org/docs/stable/data.html#disable-automatic-batching 

Using a DataGenerator to sample and batch data, and use DataLoader only for accelerating data transfer to GPU .

**Comment by Chriskuei** [comment]
@matthew-z Would you like to send a PR to fix this issue?

**Comment by matthew-z** [comment]
I will try when I have time, but it may break the current API.

**Comment by Zhiyu-Chen** [comment]
I guess that's why I found GPU memory  was occupied but the utility was actually 0% when I run my experiment.

**Comment by matthew-z** [comment]
Right, currently the dataloader takes much longer time than model forward and backward
