### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by surefirelin** [NTMC-Community/MatchZoo-py#112]
### Describe the bug
Processing text_right with chain_transform of Tokenize => Lowercase => PuncRemoval:  96%|█████████▌| 18113/18841 [00:10<00:00, 2020.19it/s]
Processing text_right with chain_transform of Tokenize => Lowercase => PuncRemoval:  97%|█████████▋| 18317/18841 [00:10<00:00, 2011.95it/s]
Processing text_right with chain_transform of Tokenize => Lowercase => PuncRemoval:  98%|█████████▊| 18520/18841 [00:10<00:00, 1890.53it/s]
Processing text_right with chain_transform of Tokenize => Lowercase => PuncRemoval: 100%|██████████| 18841/18841 [00:11<00:00, 1703.43it/s]

**Processing text_right with append:   0%|          | 0/18841 [00:00<?, ?it/s]**

TypeError                                 Traceback (most recent call last)
<ipython-input-5-3d899e94b02b> in <module>()
      1 preprocessor = mz.models.ArcI.get_default_preprocessor()
----> 2 train_processed = preprocessor.fit_transform(train_pack)
      3 valid_processed = preprocessor.transform(valid_pack)

/home/anaconda3/lib/python3.6/site-packages/matchzoo/engine/base_preprocessor.py in fit_transform(self, data_pack, verbose)
     95         :param verbose: Verbosity.
     96         """
---> 97         return self.fit(data_pack, verbose=verbose) \
     98             .transform(data_pack, verbose=verbose)
     99 

/home/anaconda3/lib/python3.6/site-packages/matchzoo/preprocessors/basic_preprocessor.py in fit(self, data_pack, verbose)
    108                                                        flatten=False,
    109                                                        mode='right',
--> 110                                                        verbose=verbose)
    111         data_pack = data_pack.apply_on_text(fitted_filter_unit.transform,
    112                                             mode='right', verbose=verbose)

/home/anaconda3/lib/python3.6/site-packages/matchzoo/preprocessors/build_unit_from_data_pack.py in build_unit_from_data_pack(unit, data_pack, mode, flatten, verbose)
     30         data_pack.apply_on_text(corpus.extend, mode=mode, verbose=verbose)
     31     else:
---> 32         data_pack.apply_on_text(corpus.append, mode=mode, verbose=verbose)
     33     if verbose:
     34         description = 'Building ' + unit.__class__.__name__ + \

/home/anaconda3/lib/python3.6/site-packages/matchzoo/data_pack/data_pack.py in wrapper(self, inplace, *args, **kwargs)
    244                 target = self.copy()
    245 
--> 246             func(target, *args, **kwargs)
    247 
    248             if not inplace:

/home/anaconda3/lib/python3.6/site-packages/matchzoo/data_pack/data_pack.py in apply_on_text(self, func, mode, rename, verbose)
    399             self._apply_on_text_left(func, rename, verbose=verbose)
    400         elif mode == 'right':
--> 401             self._apply_on_text_right(func, rename, verbose=verbose)
    402         else:
    403             raise ValueError(f"{mode} is not a valid mode type."

/home/anaconda3/lib/python3.6/site-packages/matchzoo/data_pack/data_pack.py in _apply_on_text_right(self, func, rename, verbose)
    408         if verbose:
    409             tqdm.pandas(desc="Processing " + name + " with " + func.__name__)
--> 410             self._right[name] = self._right['text_right'].progress_apply(func)
    411         else:
    412             self._right[name] = self._right['text_right'].apply(func)

/home/anaconda3/lib/python3.6/site-packages/tqdm/std.py in inner(df, func, *args, **kwargs)

/home/anaconda3/lib/python3.6/site-packages/pandas/core/base.py in _is_builtin_func(self, arg)
    658         otherwise return the arg
    659         """
--> 660         return self._builtin_table.get(arg, arg)
    661 
    662 

TypeError: unhashable type: 'list'

**Comment by Chriskuei** [comment]
#106

**Comment by surefirelin** [comment]
I have tried pip install tqdm==4.38.0, but it still doesn't work..

**Comment by surefirelin** [comment]
restart jupyter notebook..it works..thx..
