### ISSUE TITLE
Auto-prepare does not work with some models

### ISSUE THREAD

**Issue by littlewine** [NTMC-Community/MatchZoo-py#135]
Hello everyone, and thanks a lot for this amazing framework!

Auto-preparer does not seem to work with some specific models, in particular: DSSM and CDSSM. I am not sure whether this is an exhaustive list, but I tried quite a few more (ArcI, DRMM, KNRM, ConvKNRM, MatchSRNN & MVLSTM) and they seemed to be working as expected.

### To Reproduce

```
import torch
import matchzoo as mz

task = mz.tasks.Ranking(losses=mz.losses.RankCrossEntropyLoss(num_neg=4))
task.metrics = [
    mz.metrics.NormalizedDiscountedCumulativeGain(k=20),
    mz.metrics.MeanAveragePrecision()
]

# Prepare input data
train_pack = mz.datasets.wiki_qa.load_data('train', task=task)
valid_pack = mz.datasets.wiki_qa.load_data('dev', task=task)

# Auto prepare model etc.

preparer = mz.auto.Preparer(task)

model_class = mz.models.DSSM
# or
model_class = mz.models.CDSSM

model, prpr, dsb, dlb = preparer.prepare(model_class,
                                         train_pack
                                         )



train_prepr = prpr.transform(train_pack)
valid_prepr = prpr.transform(valid_pack)

train_dataset = dsb.build(train_prepr)
valid_dataset = dsb.build(valid_prepr)

train_dl = dlb.build(train_dataset)
valid_dl = dlb.build(valid_dataset)


# make it (T)rain
optimizer = torch.optim.Adam(model.parameters())

trainer = mz.trainers.Trainer(
    model=model,
    optimizer=optimizer,
    trainloader=train_dl,
    validloader=valid_dl,
    epochs=2
)

trainer.run()

```

For CDSSM I get `RuntimeError: Given groups=1, weight of size 3 419 3, expected input[40, 9654, 11] to have 419 channels, but got 9654 channels instead`.

My matchzoo.__version__ == 1.1.1

**Comment by Chriskuei** [comment]
You need to specify the vocab size when the model is DSSM and CDSSM https://github.com/NTMC-Community/MatchZoo-py/blob/49548ad4dd7da4c890ac786a09d9df9172c3af47/matchzoo/models/dssm.py#L33

You can refer to the [tutorial](https://github.com/NTMC-Community/MatchZoo-py/blob/master/tutorials/ranking/cdssm.ipynb) for more details.

**Comment by littlewine** [comment]
Oh I see. thank you
