### ISSUE TITLE
KeyError:'ngram_left'

### ISSUE THREAD

**Issue by ouyaya** [NTMC-Community/MatchZoo-py#139]
Hi, I encountered a data processing problem. When I call the diin.py model, I use this model default padding callback.
`@classmethod
def get_default_padding_callback(
cls,
fixed_length_left: int = 10,
fixed_length_right: int = 30,
pad_word_value: typing.Union[int, str] = 0,
pad_word_mode: str = 'pre',
with_ngram: bool = True,
fixed_ngram_length: int = None,
pad_ngram_value: typing.Union[int, str] = 0,
pad_ngram_mode: str = 'pre'
) -> BaseCallback:

    return callbacks.BasicPadding(
        fixed_length_left=fixed_length_left,
        fixed_length_right=fixed_length_right,
        pad_word_value=pad_word_value,
        pad_word_mode=pad_word_mode,
        with_ngram=with_ngram,
        fixed_ngram_length=fixed_ngram_length,
        pad_ngram_value=pad_ngram_value,
        pad_ngram_mode=pad_ngram_mode
    )`
Then it is processed in the padding.py file:
`if self._with_ngram: 
    ngram_length_left = max([len(w) for k in x['ngram_left'] for w in k]) 
    ngram_length_right = max([len(w) for k in x['ngram_right'] for w in k])`
But here I encountered an error：
KeyError:'ngram_left'
Do you know how this should be solved?

**Comment by ud2195** [comment]
@ouyaya were you able to solve this?
