### ISSUE TITLE
bert model

### ISSUE THREAD

**Issue by xuezzz** [NTMC-Community/MatchZoo-py#142]
I have get an error when i run your example of bert model, could you tell mw how to solve it ? Thanks!

padding_callback = mz.models.Bert.get_default_padding_callback()
trainloader = mz.dataloader.DataLoader(
    dataset=trainset,
    batch_size=20,
    stage='train',
    resample=True,
    sort=False,
    callback=padding_callback
)
testloader = mz.dataloader.DataLoader(
    dataset=testset,
    batch_size=20,
    stage='dev',
    callback=padding_callback
)

TypeError                                 Traceback (most recent call last)
<ipython-input-5-2c8844ca8335> in <module>
      6     resample=True,
      7     sort=False,
----> 8     callback=padding_callback
      9 )
     10 testloader = mz.dataloader.DataLoader(

TypeError: __init__() got an unexpected keyword argument 'batch_size'

**Comment by Chriskuei** [comment]
You can refer to this [tutorial](https://github.com/NTMC-Community/MatchZoo-py/blob/update_tutorials/tutorials/ranking/esim.ipynb)

**Comment by xuezzz** [comment]
> You can refer to this [tutorial](https://github.com/NTMC-Community/MatchZoo-py/blob/update_tutorials/tutorials/ranking/esim.ipynb)

Yes, I have run it,but have the same error...

**Comment by Chriskuei** [comment]
The parameter `batch_size` is moved to `Dataset` in MatchZoo v1.1

**Comment by xuezzz** [comment]
> The parameter `batch_size` is moved to `Dataset` in MatchZoo v1.1
The problem is solved! Thanks!
