### ISSUE TITLE
Implement the BiMPM model

### ISSUE THREAD

**Issue by rgtjf** [NTMC-Community/MatchZoo-py#28]

**Comment by lis-kp** [comment]
hi, I am having trouble trying to save the model using
1) evaluate = mz.callbacks.EvaluateAllMetrics(model, x=valid_x, y=valid_y, batch_size=16, once_every=1, model_save_path='path_to_model')
and 
2) model.save('my_model')

I get the following error in both cases: 
TypeError: can't pickle SwigPyObject objects

Does anyone have an idea on how to solve this? 
thanks a lot!

**Comment by rgtjf** [comment]
[Iter-160 Loss-0.109]:
  Validation: normalized_discounted_cumulative_gain@3(0.0): 0.6114 - normalized_discounted_cumulative_gain@5(0.0): 0.6667 - mean_average_precision(0.0): 0.622
