### ISSUE TITLE
RE2  (Simple and Effective Text Matching with Richer Alignment Features)

### ISSUE THREAD

**Issue by mrlonely001** [NTMC-Community/MatchZoo-py#56]
As the title mentioned ，it's  a new model for sentence matching .  FYI

**Comment by Chriskuei** [comment]
Are you implementing this model?

**Comment by mrlonely001** [comment]
Sorry for disturbing. I didn't read the doc carefully before . Mathczoo is a nice project, I eager to be a contributer , if the group has no time to implement this model， maybe i can try.   (ps: the author for this model has opensource the tensorflow version , all we should do is translate it to pytorch version )

**Comment by Chriskuei** [comment]
Welcome to be a contributor! Before you start to implement this model, I recommend you first read the [CONTRIBUTING GUIDE](https://github.com/NTMC-Community/MatchZoo-py/blob/master/CONTRIBUTING.md).

Feel free to ask us if you have any problems~
