### ISSUE TITLE
RuntimeError: The size of tensor a (68) must match the size of tensor b (67) at non-singleton dimension 0

### ISSUE THREAD

**Issue by lhohoz** [NTMC-Community/MatchZoo-py#58]
Hi!

I encountered an error prompt (such as title) when running dssm.ipynb on my local machine. My environment is Windows10+Pytorch1.2+cuda9.0. Could you please tell me the solution.

Thanks.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-041e2033e90a> in <module>
----> 1 trainer.run()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matchzoo\trainers\trainer.py in run(self)
    230         for epoch in range(self._start_epoch, self._epochs + 1):
    231             self._epoch = epoch
--> 232             self._run_epoch()
    233             self._run_scheduler()
    234             if self._early_stopping.should_stop_early:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matchzoo\trainers\trainer.py in _run_epoch(self)
    258                 # Caculate all losses and sum them up
    259                 loss = torch.sum(
--> 260                     *[c(outputs, target) for c in self._criterions]
    261                 )
    262                 self._backward(loss)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matchzoo\trainers\trainer.py in <listcomp>(.0)
    258                 # Caculate all losses and sum them up
    259                 loss = torch.sum(
--> 260                     *[c(outputs, target) for c in self._criterions]
    261                 )
    262                 self._backward(loss)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matchzoo\losses\rank_hinge_loss.py in forward(self, y_pred, y_true)
     63             y_pos, y_neg, y_true,
     64             margin=self.margin,
---> 65             reduction=self.reduction
     66         )
     67 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py in margin_ranking_loss(input1, input2, target, margin, size_average, reduce, reduction)
   2206         raise RuntimeError(("margin_ranking_loss does not support scalars, got sizes: "
   2207                             "input1: {}, input2: {}, target: {} ".format(input1.size(), input2.size(), target.size())))
-> 2208     return torch.margin_ranking_loss(input1, input2, target, margin, reduction_enum)
   2209 
   2210 

RuntimeError: The size of tensor a (68) must match the size of tensor b (67) at non-singleton dimension 0

**Comment by Chriskuei** [comment]
Hi, did you modify any code in the tutorial?

**Comment by lhohoz** [comment]
Thank you your reply, In fact, I ran two versions, one with no changes and the other with minor changes, but with the same error.

**Comment by caiyinqiong** [comment]
Hi! 
From the RuntimeError Traceback, it shows that error occurred in calling RankHingeLoss.forward().
But we define `ranking_task = mz.tasks.Ranking(losses=mz.losses.RankCrossEntropyLoss(num_neg=4))` in dssm.ipynb.
So, please ensure that every code block in the tutorial is executed correctly.

Additionally, when you modify the code, please ensure the `num_neg` param passed to RankCrossEntropyLoss(or RankHingeLoss) and DataLoader are identical. If not, similar error will occur.

**Comment by lhohoz** [comment]
Hi caiyinqiong,

Thank you for your answer. Problem solved. I used the wrong error function.

Thanks.

**Comment by Chriskuei** [comment]
I am glad things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.
