### ISSUE TITLE
AttributeError: type object 'Path' has no attribute 'expanduser'

### ISSUE THREAD

**Issue by ZahraGithub** [NTMC-Community/MatchZoo-py#72]
Hi,
My python versions is 2.7 and 3.6.
When I import torch and then import matchzoo as mz in python 2.7 I receive this error:
"AttributeError: type object 'Path' has no attribute 'expanduser'"
and in python3 I receive this error:
"ImportError: cannot import name 'ensure_object'"
while matchzoo-py installed completely successfully. 
I would appreciate it if you guide me.

Many thanks before all

**Comment by Chriskuei** [comment]
Hi Zahra,

MatchZoo only supports Python 3.6+. Can you provide more details about the error?
