### ISSUE TITLE
Load Data

### ISSUE THREAD

**Issue by ZahraGithub** [NTMC-Community/MatchZoo-py#73]
Hi,

I have Robust04 data for testing drmm. I do not know how to load this data.
I would appreciate it if you guide me.

Many thanks before all

**Comment by ChrisRBXiong** [comment]
You need to format your data into the desired format first, and then write a function to load it as matchzoo.DataPack. 

The data should be formated into an csv file, whose columns are row_index, id_left, text_left, id_right, text_right and label. Take QA task as an example. The question is "how a rocket engine works" and the true answer is "A rocket engine, or simply ""rocket"", is a jet engine that uses only stored propellant mass for forming its high speed propulsive jet ." Then the instance can be formated into

> 0,Q1,how a rocket engine works,D1,"A rocket engine, or simply ""rocket"", is a jet engine that uses only stored propellant mass for forming its high speed propulsive jet .",1.0

You can check "[matchzoo/datasets/toy](https://github.com/NTMC-Community/MatchZoo-py/tree/master/matchzoo/datasets/toy)", it is a toy dataset example that illustrated the data format and how to write the load_data function.

**Comment by ZahraGithub** [comment]
Thanks for your reply.
My train data is about 182378 records. Each record has a doc with length of at most 316 tokens. Do you think it is possible to have a csv file with more than 182378 docs*316 tokens*8 character in ram?
I think it is not possible. 

I would appreciate it if you guide me.
Many thanks before all

**Comment by ZahraGithub** [comment]
Dear ChrisRBXiong,

I wish you answer my question a little bit sooner since I am in a terrific force and as you know process is time-consuming.

Thanks before all

**Comment by ZahraGithub** [comment]
Thanks for your clear reply.
