### ISSUE TITLE
Load_glove_embedding with toy dataset

### ISSUE THREAD

**Issue by ZahraGithub** [NTMC-Community/MatchZoo-py#79]
Hi,

When I use toy dataset I see the following error in this line:
`glove_embedding = mz.datasets.embeddings.load_glove_embedding(dimension=300)`
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6148: character maps to <undefined>`

I would appreciate it if you guide me how to solve this problem.
I wish you answer my questions a little bit faster since the time passes quickly :)

Thanks

**Comment by Chriskuei** [comment]
Can you provide your code snippet so that we can reproduce the error?

**Comment by ZahraGithub** [comment]
Thanks for your fast reply. Of course, here you are:

`import torch
import matchzoo as mz
if __name__ == '__main__':
    glove_embedding = mz.datasets.embeddings.load_glove_embedding(dimension=50)`

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2273: character maps to <undefined>`

I searched this error and found that in embedding.py lines 90 and 96:
`with open(file_path, 'r') as f:`
could be changed to 
`with open(file_path, 'r', encoding="utf8") as f:`

Do you agree with me?
Although it is interesting that know the reason since we are working on English documents.

Thanks

**Comment by Chriskuei** [comment]
Hi Zahra,

I tested the code you provided, but no error. Which version of Python do you use? MatchZoo-py only supports Python 3.6+

**Comment by ZahraGithub** [comment]
Hi Chris,

Python 3.6.8. Also, I installed matchzoo-py successfully.

**Comment by Chriskuei** [comment]
You can add `encoding="utf-8"` by yourself and have a try.

**Comment by ZahraGithub** [comment]
Yes, you are right. Thanks.

Excuse me dear Chris, I sent another question in issue #73 yesterday. Would you please check it out?

**Comment by ZahraGithub** [comment]
Thanks, you are right.
