### ISSUE TITLE
为什么demo跑出来的acc值都不变，有没有交流群

### ISSUE THREAD

**Issue by will-wiki** [NTMC-Community/MatchZoo-py#98]
想问问有没有交流群可以交流心得的
想问下，为什么跑项目esim的demo例子，多个epoch的acc值一直不变。同样的我改成了中文的，情况也是一样，能跑通但是每个epoch的验证acc值都是不变

**Comment by Chriskuei** [comment]
For less formal discussion we have a chat room on WeChat (mostly Chinese speakers). MatchZoo-py core developers are almost always present; feel free to find us there and we're happy to chat. Please add YQ-Cai1198593462 as your WeChat friend, she will invite you to join the chat room.

**Comment by will-wiki** [comment]
嗯嗯 谢谢～
