### ISSUE TITLE
How to use gpu to run trainer?

### ISSUE THREAD

**Issue by czt616** [NTMC-Community/MatchZoo-py#99]
In the MatchZoo-py/tutorials/ranking/drmm.ipynb, I change the parameter 'device' in trainloader = mz.dataloader.DataLoader and trainer = mz.trainers.Trainer as device = torch.device('cuda'). The nvidia-smi shows I have an available gpu. But it seems still ran on cpu. Can you help me with this? Thank you!

**Comment by Chriskuei** [comment]
Please check if CUDA is currently available by using `torch.cuda.is_available()`.

**Comment by czt616** [comment]
torch.cuda.is_available() returned true. But the speed seems the same as running on CPU.

**Comment by lianrzh** [comment]
@czt616 Try to change the parameter 'device' by setting `device=torch.device('cpu')` to check the speed of cpu. The default value of 'device' is torch.device('cuda') when CUDA is available.

**Comment by PathricLee** [comment]
I have the same problems, when torch.cuda.is_available() returned true, but the speed is still now. the gpu rate of utilization is about 10%  and most of time is 0%.

**Comment by Zhiyu-Chen** [comment]
It may result from this issue: https://github.com/NTMC-Community/MatchZoo-py/issues/109

**Comment by Chriskuei** [comment]
The latest version of MatchZoo-py (v1.1.1) has solved this issue

**Comment by czt616** [comment]
> The latest version of MatchZoo-py (v1.1.1) has solved this issue

When I run the drmm code in tutorials, there is an error says:
Traceback (most recent call last):
  File "pydrmm.py", line 64, in <module>
    callback=padding_callback
TypeError: __init__() got an unexpected keyword argument 'batch_size'
Why it occured?

**Comment by Chriskuei** [comment]
> > The latest version of MatchZoo-py (v1.1.1) has solved this issue
> 
> When I run the drmm code in tutorials, there is an error says:
> Traceback (most recent call last):
> File "pydrmm.py", line 64, in 
> callback=padding_callback
> TypeError: **init**() got an unexpected keyword argument 'batch_size'
> Why it occured?

DRMM tutorial has not been updated yet, you can refer to [DRMMTKS tutorial](https://github.com/NTMC-Community/MatchZoo-py/blob/master/tutorials/ranking/drmmtks.ipynb)
